<?php
/**
 * @file
 * A block that displays Global Privacy Control settings from the browser.
 */

/**
 * Implements hook_config_info().
 */
function gpc_config_info() {
  $prefixes['gpc.settings'] = array(
    'label' => t('GPC Visual Confirmation settings'),
    'group' => t('Configuration'),
  );
  return $prefixes;
}

/**
 * Implements hook_permission().
 */
function gpc_permission() {
  $permissions = array(
    'confugre gpc visual confirmation' => array(
      'title' => t('Configure Global Privacy Control Visual Confirmation.'),
    ),
  );

  return $permissions;
}

/**
 * Implements hook_menu().
 */
function gpc_menu() {
  $items = array();

  $items['admin/config/user-interface/gpc'] = array(
    'title' => 'Configure GPC Visual Confirmation',
    'description' => t('Adjust settings for Global Privacy Control Visual Confirmation.'),
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('gpc_config_form'),
    'access arguments' => array('confugre gpc visual confirmation'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'gpc.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_block_info().
 */
function gpc_block_info() {
  $blocks['gpc-status'] = array(
    'info' => t('GPC Visual Confirmation'),
    'description' => t('Displays the viewer\'s Global Privacy Control settings from the browser.'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function gpc_block_view($delta = '', $settings = array(), $contexts = array()) {
  // This example is adapted from node.module.
  $block = array();

  switch ($delta) {
    case 'gpc-status':

      $enabled = gpc_is_enabled();
      $icon = _gpc_build_icon($enabled);
      $text = _gpc_build_text($enabled);

      $path = backdrop_get_path('module', 'gpc');
      $block['subject'] = '';
      $block['content'] = array(
        '#theme' => 'container__gpc',
        '#children' => $icon . '<span>' . $text . '</span>',
        '#attributes' => array('class' => array('gpc-banner')),
        '#attached' => array('css' => array($path . '/css/gpc.css')),
      );
      if (isset($settings['background']) && $settings['background'] != 'none') {
        $block['content']['#attributes']['class'][] = $settings['background'];
      }
      if (isset($settings['position']) && $settings['position'] != 'none') {
        $block['content']['#attributes']['class'][] = $settings['position'];
      }

      break;
  }

  return $block;
}

/**
 * Implements hook_block_configure().
 */
function gpc_block_configure($delta = '', $settings = array()) {
  // This example comes from node.module.
  $form = array();

  if ($delta == 'gpc-status') {
    $settings += array(
      'background' => 'dark',
      'position' => 'none',
      'link' => 'yeslink',
    );

    $form['background'] = array(
      '#type' => 'radios',
      '#title' => t('Block background color'),
      '#default_value' => $settings['background'],
      '#options' => array(
        'none' => t('None'),
        'dark' => t('Black'),
        'light' => t('White'),
      ),
    );
    $form['position'] = array(
      '#type' => 'radios',
      '#title' => t('Special Positioning'),
      '#default_value' => $settings['position'],
      '#options' => array(
        'none' => t('None'),
        'fixed-top' => t('Fixed at Top: Anchors the banner to the top of the browser window'),
        'fixed-bottom' => t('Fixed at Bottom: Anchors the banner to the bottom of the browser window'),
      ),
    );
    $form['link'] = array(
      '#type' => 'radios',
      '#title' => t('Include Download Link'),
      '#default_value' => $settings['link'],
      '#options' => array(
        'nolink' => t('No'),
        'yeslink' => t('Yes'),
      ),
    );
  }

  return $form;
}

/*******************************************************************************
 * Theme / Preprocess functions.
 ******************************************************************************/

/**
 * Prepares variables for Layout templates.
 */
function gpc_preprocess_page(&$variables) {
  // Performance: Skip this entirely for AJAX requests.
  if (!backdrop_is_html()) {
    return;
  }

  $config = config('gpc.settings');
  if ($config->get('position') != 'none') {
    // Add a banner.
    $enabled = gpc_is_enabled();
    $icon = _gpc_build_icon($enabled);
    $text = _gpc_build_text($enabled);
    $path = backdrop_get_path('module', 'gpc');
    $banner = array(
      '#theme' => 'container__gpc',
      '#children' => $icon . '<span>' . $text . '</span>',
      '#attributes' => array(
        'id' => 'gpc-banner',
        'class' => array('gpc-banner'),
      ),
      '#attached' => array('css' => array($path . '/css/gpc.css')),
    );
    $background = $config->get('background');
    if ($background != 'none') {
      $banner['#attributes']['class'][] = $background;
    }
    $position = $config->get('position');
    if ($position != 'none') {
      $banner['#attributes']['class'][] = $position;
    }

    $variables['page_bottom'] .= backdrop_render($banner);
  }
}

/*******************************************************************************
 * Helper functions.
 ******************************************************************************/

/**
 * Helper function: determines whether GPC is enabled.
 */
function gpc_is_enabled() {
  $enabled = &backdrop_static(__FUNCTION__);
  if (!isset($enabled)) {
    $enabled = isset($_SERVER['HTTP_SEC_GPC']) && $_SERVER['HTTP_SEC_GPC'] === '1';
  }

  return $enabled;
}

/**
 * Helper function: Builds the GPC icon.
 */
function _gpc_build_text($enabled) {
  if (!isset($enabled)) {
    $enabled = gpc_is_enabled();
  }
  if ($enabled) {
    $text = t('Your Global Privacy Control opt-out prefernce has been detected.');
  }
  else {
    $download_url = 'https://globalprivacycontrol.org/#download';
    $pdf_url = 'https://globalprivacycontrol.org/GPC_for_Users.pdf';
    if (isset($settings['link']) && $settings['link'] == 'yeslink') {
      $replacements = array('@url' => $pdf_url);
      $link_text = 'We could not detect a &nbsp;<a href="@url">privacy preference</a>.<span class="lg-screen"> If you would like websites to recognize your privacy choices automatically, please check your browser privacy settings.</span>';
    }
    else {
      $replacements = array();
      $link_text = 'Privacy preference not detected.<span class="lg-screen">  If you would like websites to recognize your privacy choices automatically, please check your browser privacy settings.</span>';
    }

    $text = t($link_text, $replacements);
  }

  return $text;
}

/**
 * Helper function: Builds the GPC icon.
 */
function _gpc_build_icon($enabled) {
  if (!isset($enabled)) {
    $enabled = gpc_is_enabled();
  }
  $icon_options = array(
    'attributes' => array(
      'width' => '25',
      'class' => array('gpc-icon'),
    ),
  );
  if ($enabled) {
    $icon_options['attributes']['class'][] = 'gpc-enabled';
    $icon = icon('check-circle', $icon_options);
  }
  else {
    $icon_options['attributes']['class'][] = 'gpc-disabled';
    $icon = icon('warning-circle', $icon_options);
  }

  return $icon;
}
